development:
  adapter: postgresql
  encoding: unicode
  database: db_ngdecor_development
  pool: 5
  username: 
  password:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: db_ngdecor_test
  pool: 5
  username:
  password:
